### ISSUE TITLE
Sylk-Pushserver Not Starting After Upgrade To V2.0.0 on Opensips 3.0

### ISSUE THREAD

**Issue by hasanr68** [AGProjects/sylk-pushserver#12]
Hi all,

I am using sylk-pushserver version 2 on Opensips 3.0. I tried upgrading and restarting the server, but get the following error:

Feb 14 13:16:30 ip-172-31-27-223 sylk-pushserver[7363]: Traceback (most recent call last):
Feb 14 13:16:30 ip-172-31-27-223 sylk-pushserver[7363]:   File "/usr/bin/sylk-pushserver", line 6, in <module>
Feb 14 13:16:30 ip-172-31-27-223 sylk-pushserver[7363]:     import uvicorn
Feb 14 13:16:30 ip-172-31-27-223 sylk-pushserver[7363]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/uvicorn/__init__.p
Feb 14 13:16:30 ip-172-31-27-223 sylk-pushserver[7363]:     from uvicorn.main import Server, main, run
Feb 14 13:16:30 ip-172-31-27-223 sylk-pushserver[7363]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/uvicorn/main.py",
Feb 14 13:16:30 ip-172-31-27-223 sylk-pushserver[7363]:     LEVEL_CHOICES = click.Choice(list(LOG_LEVELS.keys()))
Feb 14 13:16:30 ip-172-31-27-223 sylk-pushserver[7363]: AttributeError: module 'click' has no attribute 'Choice'

Do I need to make any changes pls?

**Comment by tijmenNL** [comment]
How did you install it? Which OS are you using?

**Comment by hasanr68** [comment]
Thanks for the quick response.
apt-get upgrade sylk-pushserver.

Debian GNU/Linux 10 (buster)

**Comment by tijmenNL** [comment]
Can you check what ` dpkg --list | grep python3-click` outputs?

**Comment by hasanr68** [comment]
I get no output.

**Comment by tijmenNL** [comment]
Then please install python3-click

**Comment by hasanr68** [comment]
Thanks - get this output now:
ii  python3-click                       7.0-1                                 all          Wrapper around optparse for command line utilities - Python 3.x

**Comment by tijmenNL** [comment]
Ok, please try to run the pushserver again, it should work now.

**Comment by hasanr68** [comment]
And getting this error:
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver] Traceback (most recent call last):
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]   File "/usr/bin/sylk-pushserver", line 126, in <module>
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]     access_log=False, log_level='error')
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]     server.run()
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]     self.config.setup_event_loop()
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]     loop_setup(use_subprocess=self.use_subprocess)
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]     uvloop_setup(use_subprocess=use_subprocess)
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver]     asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
Feb 14 13:49:23 ip-172-31-27-223 sylk-pushserver[11749]: ERROR    [sylk-pushserver] AttributeError: module 'uvloop' has no attribute 'EventLoopPolicy'

**Comment by tijmenNL** [comment]
install python3-uvloop

**Comment by hasanr68** [comment]
Thanks - done. Apologies for the trouble!

**Comment by tijmenNL** [comment]
Does it work now? 

I guess the deb is missing some dependencies. It will be fixed in the next version.

**Comment by hasanr68** [comment]
It has started, but doesn't seem to be pushing notifications.

**Comment by tijmenNL** [comment]
If that is the case, please open a separate issue with the relevant details.

**Comment by hasanr68** [comment]
OK
